/* Generated from the All Live Baseball app — do not hand-edit.
   Regenerate whenever the rosters or songs change there, so the two
   apps can't drift apart.

   teams:   team -> its players, already sorted A-Z by first name
   songs:   player -> the song they use now (missing = nobody knows)
   history: player -> every song their team page has listed, newest
            first, with the date it was logged. Only players who have
            used more than one appear here. */
const DATA = {
"teams": {
"Additional players": [
"Brennan Bernardino",
"Christian Yelich",
"Edouard Julien",
"Jacob Wilson",
"Jake McCarthy",
"Jordan Romano",
"Michael Lorenzen",
"Tyler Freeman",
"Willi Castro"
],
"Arizona Diamondbacks": [
"A.J. Puk",
"Adrian Del Castillo",
"Andrew Hoffmann",
"Andrew Saalfrank",
"Blake Walston",
"Brandon Pfaadt",
"Brandyn Garcia",
"Corbin Burnes",
"Corbin Carroll",
"Cristian Mena",
"Drey Jameson",
"Dylan Ray",
"Eduardo Rodriguez",
"Gabriel Moreno",
"Geraldo Perdomo",
"Gerardo Carrillo",
"Ildemaro Vargas",
"James McCann",
"Jonathan Loáisiga",
"Jordan Lawlar",
"Jorge Barrosa",
"Jose Cabrera",
"Jose Fernandez",
"Juan Burgos",
"Juan Morillo",
"Justin Martinez",
"Kade Strowd",
"Ketel Marte",
"Kevin Ginkel",
"Kohl Drake",
"Lars Nootbaar",
"Lourdes Gurriel Jr.",
"LuJames Groover",
"Max Kepler",
"Merrill Kelly",
"Michael Soroka",
"Mitch Bratt",
"Nolan Arenado",
"Paul Sewald",
"Philip Abner",
"Ryan Thompson",
"Ryan Waldschmidt",
"Ryne Nelson",
"Taylor Clarke",
"Tim Tawa",
"Tommy Troy",
"Tyler Locklear",
"Zac Gallen"
],
"Athletics": [
"Aaron Civale",
"Alika Williams",
"Braden Nett",
"Brent Rooker",
"Brian Serven",
"Brooks Kriske",
"Darell Hernaiz",
"Denzel Clarke",
"Gunnar Hoglund",
"Hayden Juenger",
"Henry Baez",
"Jacob Lopez",
"Jeff McNeil",
"Jeffrey Springs",
"Joey Estes",
"Joey Meneses",
"Jonah Heim",
"Joshua Kuroda Grauer",
"Justin Sterner",
"Kade Morris",
"Lawrence Butler",
"Luis Morales",
"Luis Severino",
"Mark Leiter Jr.",
"Mason Barnett",
"Nick Kurtz",
"Scott Blewett",
"Shea Langeliers",
"Tommy White",
"Tyler Soderstrom",
"Yunior Tur",
"Zack Gelof"
],
"Atlanta Braves": [
"AJ Smith-Shawver",
"Anthony Molina",
"Austin Riley",
"Brewer Hicklen",
"Bryce Elder",
"Chris Sale",
"Connor Thomas",
"DaShawn Keirsey Jr.",
"Danny Young",
"Dominic Smith",
"Drake Baldwin",
"Duncan Davitt",
"Dylan Dodd",
"Dylan Lee",
"Eli White",
"Grant Holmes",
"Ha-Seong Kim",
"Hayden Harris",
"Hurston Waldrep",
"JR Ritchie",
"James Karinchak",
"Jim Jarvis",
"Joe Jiménez",
"Joey Bart",
"Joey Wentz",
"Jorge Mateo",
"Kyle Farmer",
"Martín Pérez",
"Matt Olson",
"Mauricio Dubón",
"Michael Harris II",
"Mike Yastrzemski",
"Nacho Alvarez Jr.",
"Owen Murphy",
"Ozzie Albies",
"Raisel Iglesias",
"Reynaldo López",
"Robert Suarez",
"Rolddy Munoz",
"Ronald Acuña Jr.",
"Sean Murphy",
"Spencer Schwellenbach",
"Spencer Strider",
"Tyler Kinley",
"Tyler Uberstine"
],
"Baltimore Orioles": [
"Albert Suárez",
"Alex Hoppe",
"Andrew Kittredge",
"Anthony Nunez",
"Blaze Alexander",
"Brandon Young",
"Cade Povich",
"Cam Sanders",
"Cameron Foster",
"Cameron Weston",
"Carlos Narváez",
"Chris Bassitt",
"Christian Encarnacion-Strand",
"Christian Franklin",
"Coby Mayo",
"Codi Heuer",
"Colin Selby",
"Colton Cowser",
"Dylan Beavers",
"Félix Bautista",
"Grant Wolfram",
"Gunnar Henderson",
"Heston Kjerstad",
"Jackson Holliday",
"Jeremiah Jackson",
"Jordan Westburg",
"Josh Walker",
"Keegan Akin",
"Kyle Bradish",
"Leody Taveras",
"Nick Raquet",
"Pete Alonso",
"Rece Hinds",
"Reed Trimble",
"Rico Garcia",
"Ryan Helsley",
"Ryan Mountcastle",
"Samuel Basallo",
"Shane Baz",
"Taylor Ward",
"Trevor Rogers",
"Trey Gibson",
"Tyler O'Neill",
"Tyler Wells",
"Yaramil Hiraldo",
"Yennier Cano",
"Yohel Pozo",
"Yosver Zulueta",
"Zach Eflin"
],
"Boston Red Sox": [
"Adley Rutschman",
"Alec Gamboa",
"Andruw Monasterio",
"Anthony Seigler",
"Aroldis Chapman",
"Brayan Bello",
"Brett Harris",
"Caleb Durbin",
"Carlos Narváez",
"Ceddanne Rafaela",
"Connor Wong",
"Curtis Mead",
"Danny Coulombe",
"Eduardo Rivera",
"Eli White",
"Erik Miller",
"Garrett Crochet",
"Garrett Whitlock",
"Greg Weissert",
"Isiah KinerFalefa",
"Jahmai Jones",
"Jake Bennett",
"Jake Rogers",
"Jarren Duran",
"Johan Oviedo",
"Jovani Moran",
"Jovani Morán",
"Justin Slaten",
"Kristian Campbell",
"Kutter Crawford",
"Masataka Yoshida",
"Mickey Gasper",
"Nate Eaton",
"Nick Sogard",
"Patrick Sandoval",
"Payton Tolle",
"Ranger Suárez",
"Raymond Burgos",
"Roman Anthony",
"Romy Gonzalez",
"Ryan Watson",
"Seth Martinez",
"Sonny Gray",
"Tanner Houck",
"Tayron Guerrero",
"Trevor Story",
"Triston Casas",
"Tsung-Che Cheng",
"Tyler Samaniego",
"Willson Contreras",
"Wilyer Abreu",
"Zack Kelly"
],
"Chicago Cubs": [
"Aaron Civale",
"Alex Bregman",
"Antoine Kelly",
"Ben Brown",
"Braxton Garrett",
"Cade Horton",
"Caleb Thielbar",
"Carson Kelly",
"Clay Holmes",
"Colin Rea",
"Daniel Palencia",
"Dansby Swanson",
"David Peterson",
"Drew Pomeranz",
"Edward Cabrera",
"Ethan Roberts",
"Gavin Hollowell",
"Hoby Milner",
"Hunter Harvey",
"Ian Happ",
"Jacob Webb",
"James Triantos",
"Jameson Taillon",
"Javier Assad",
"Jayden Murray",
"Jordan Wicks",
"Justin Dean",
"Justin Steele",
"Kevin Alcántara",
"Kevin Gausman",
"Luke Little",
"Matt Shaw",
"Matthew Boyd",
"Michael Busch",
"Michael Conforto",
"Miguel Amaya",
"Moisés Ballesteros",
"Nico Hoerner",
"Pedro Ramirez",
"Pete Crow-Armstrong",
"Phil Maton",
"Porter Hodge",
"Riley Martin",
"Ryan Rolison",
"Ryan Zeferjahn",
"Seiya Suzuki",
"Shelby Miller",
"Shota Imanaga",
"Trent Thornton",
"Tyler Austin",
"Tyler Ferguson",
"Tyrone Taylor"
],
"Chicago White Sox": [
"Andrew Benintendi",
"Chris Murphy",
"Erick Fedde",
"Jordan Hicks",
"Luisangel Acuña",
"Miguel Vargas",
"Randal Grichuk",
"Sean Newcomb"
],
"Cincinnati Reds": [
"Andrew Abbott",
"Blake Dunn",
"Brady Singer",
"Brandon Williamson",
"Brock Burke",
"Chase Burns",
"Chase Petty",
"Connor Phillips",
"Dane Myers",
"Edwin Arroyo",
"Elly De La Cruz",
"Emilio Pagán",
"Eugenio Suárez",
"Graham Ashcraft",
"Hunter Greene",
"JJ Bleday",
"Jose Trevino",
"Ke'Bryan Hayes",
"Matt McLain",
"Nathaniel Lowe",
"Nick Lodolo",
"Noelvi Marte",
"Pierce Johnson",
"Rhett Lowder",
"Sal Stewart",
"Sam Moll",
"Spencer Steer",
"TJ Friedl",
"Tejay Antone",
"Tony Santillan",
"Tyler Stephenson",
"Zach Maxwell"
],
"Cleveland Guardians": [
"Austin Hedges",
"Brayan Rocchio",
"Cade Smith",
"Colin Holderman",
"Daniel Schneemann",
"David Fry",
"Gabriel Arias",
"Gavin Williams",
"Hunter Gaddis",
"Joey Cantillo",
"Kyle Manzardo",
"Patrick Bailey",
"Rhys Hoskins",
"Shawn Armstrong",
"Slade Cecconi",
"Tanner Bibee"
],
"Detroit Tigers": [
"Beau Brieske",
"Casey Mize",
"Colt Keith",
"Dillon Dingler",
"Drew Anderson",
"Framber Valdez",
"Hao-Yu Lee",
"Jack Flaherty",
"Jacob Waguespack",
"Jake Rogers",
"James Outman",
"Keider Montero",
"Kenley Jansen",
"Kerry Carpenter",
"Kevin McGonigle",
"Kyle Finnegan",
"Matt Vierling",
"Riley Greene",
"Spencer Torkelson",
"Tarik Skubal",
"Tyler Holton",
"Zach McKinstry"
],
"Houston Astros": [
"AJ Blubaugh",
"Brice Matthews",
"Bryan Abreu",
"Bryan King",
"Cam Smith",
"Cristian Javier",
"Hunter Brown",
"Isaac Paredes",
"Jeremy Peña",
"Jose Altuve",
"Josh Hader",
"LaMonte Wade Jr.",
"Nate Pearson",
"Nick Allen",
"Peter Lambert",
"Spencer Arrighetti",
"Steven Okert",
"Tatsuya Imai",
"Taylor Trammell",
"Yainer Diaz",
"Yordan Alvarez",
"Zach Dezenzo"
],
"Kansas City Royals": [
"Alex Lange",
"Bobby Witt Jr.",
"Carter Jensen",
"Daniel Lynch IV",
"Eli Morgan",
"Isaac Collins",
"Jac Caglianone",
"John Schreiber",
"Josh Rojas",
"Lane Thomas",
"Lucas Erceg",
"Luinder Avila",
"Luke Maile",
"Matt Strahm",
"Michael Massey",
"Nick Loftin",
"Noah Cameron",
"Salvador Perez",
"Seth Lugo",
"Starling Marte",
"Steven Cruz",
"Tyler Tolbert",
"Vinnie Pasquantino"
],
"Los Angeles Angels": [
"Brent Suter",
"Grayson Rodriguez",
"Jorge Soler",
"Jose Siri",
"Josh Lowe",
"Kirby Yates",
"Mike Trout",
"Oswald Peraza",
"Tyler Heineman",
"Vaughn Grissom",
"Wade Meckler",
"Zach Neto"
],
"Los Angeles Dodgers": [
"Alek Thomas",
"Alex Call",
"Alex Freeland",
"Alex Vesia",
"Andy Pages",
"Ben Casparius",
"Blake Snell",
"Blake Treinen",
"Bobby Miller",
"Brock Stewart",
"Brusdar Graterol",
"Chayce McDermott",
"Dalton Rushing",
"Edgardo Henriquez",
"Edwin Díaz",
"Emmet Sheehan",
"Enrique Hernández",
"Eric Lauer",
"Evan Phillips",
"Freddie Freeman",
"Gavin Stone",
"Hyeseong Kim",
"Jack Dreyer",
"Jake Cousins",
"Justin Wrobleski",
"Kyle Hurt",
"Kyle Tucker",
"Landon Knack",
"Max Muncy",
"Miguel Rojas",
"Mookie Betts",
"River Ryan",
"Roki Sasaki",
"Ryan Ward",
"Shohei Ohtani",
"Tanner Scott",
"Teoscar Hernández",
"Tommy Edman",
"Tyler Glasnow",
"Will Klein",
"Will Smith",
"Yoshinobu Yamamoto"
],
"Miami Marlins": [
"Brad Keller",
"Derek Hill",
"Esteury Ruiz",
"Eury Pérez",
"Griffin Conine",
"Heriberto Hernández",
"Janson Junk",
"Javier Sanoja",
"Kyle Stowers",
"Leo Jiménez",
"Liam Hicks",
"Otto Lopez",
"Pete Fairbanks",
"Ryan Gusto",
"Sandy Alcantara",
"Tim Mayza",
"Tyler Phillips",
"Xavier Edwards"
],
"Milwaukee Brewers": [
"Abner Uribe",
"Andrew Vaughn",
"Brice Turang",
"Bryse Wilson",
"Chad Patrick",
"Cooper Pratt",
"Garrett Mitchell",
"Gary Sánchez",
"Jacob Misiorowski",
"Jake Bauers",
"Jared Koenig",
"Joey Ortiz",
"Robert Gasser",
"Sal Frelick",
"Trevor Megill",
"William Contreras"
],
"Minnesota Twins": [
"Alex Jackson",
"Andrew Morris",
"Austin Martin",
"Bailey Ober",
"Brooks Lee",
"Joe Ryan",
"Josh Bell",
"Kendry Rojas",
"Kody Clemens",
"Kody Funderburk",
"Luke Keaschall",
"Mike Paredes",
"Royce Lewis",
"Ryan Jeffers",
"Ryan Kreidler",
"Taj Bradley",
"Taylor Rogers",
"Tommy Nance",
"Trevor Larnach",
"Tristan Gray",
"Victor Caratini",
"Yoendrys Gómez",
"Zebby Matthews"
],
"New York Mets": [
"A.J. Minter",
"Bo Bichette",
"Brooks Raley",
"Christian Scott",
"Devin Williams",
"Eric Wagaman",
"Francisco Alvarez",
"Freddy Peralta",
"Jared Young",
"Jorge Polanco",
"Juan Soto",
"Kodai Senga",
"Luis Torrens",
"Sean Manaea",
"Tobias Myers",
"Tyrone Taylor",
"Xzavion Curry"
],
"New York Yankees": [
"Amed Rosario",
"Anthony Volpe",
"Camilo Doval",
"David Bednar",
"Fernando Cruz",
"Gerrit Cole",
"José Caballero",
"Max Schuemann",
"Paul Blackburn",
"Paul Goldschmidt",
"Ryan Weathers",
"Trent Grisham"
],
"Pittsburgh Pirates": [
"Brandon Lowe",
"Bryan Reynolds",
"Carmen Mlodzinski",
"Gregory Soto",
"Henry Davis",
"Jake Mangum",
"Jared Triolo",
"Marcell Ozuna",
"Mason Montgomery",
"Mitch Keller",
"Ryan O'Hearn"
],
"San Francisco Giants": [
"Adrian Houser",
"Bryce Eldridge",
"Casey Schmitt",
"Christian Koss",
"Grant McCray",
"Jung Hoo Lee",
"Keaton Winn",
"Landen Roupp",
"Luis Arraez",
"Robbie Ray",
"Sam Hentges",
"Spencer Bivens",
"Tyler Mahle"
],
"Seattle Mariners": [
"Andrés Muñoz",
"Bryan Woo",
"Bryce Miller",
"Cal Raleigh",
"Cole Young",
"Dominic Canzone",
"Eduard Bazardo",
"Emerson Hancock",
"Gabe Speier",
"George Kirby",
"J.P. Crawford",
"Josh Naylor",
"José A. Ferrer",
"Logan Gilbert",
"Luis Castillo",
"Luke Raley",
"Mitch Garver",
"Victor Robles",
"Weston Wilson"
],
"St. Louis Cardinals": [
"Alec Burleson",
"Andre Pallante",
"Blaze Jordan",
"Bryan Torres",
"César Prieto",
"Dustin May",
"George Soriano",
"Gordon Graceffo",
"Hunter Dobbins",
"Iván Herrera",
"JJ Wetherholt",
"Jimmy Crooks",
"JoJo Romero",
"Jordan Walker",
"José Fermín",
"Justin Bruihl",
"Kyle Leahy",
"Lars Nootbaar",
"Masyn Winn",
"Matt Svanson",
"Matthew Liberatore",
"Michael McGreevy",
"Nathan Church",
"Nelson Velázquez",
"Nolan Gorman",
"Pedro Pagés",
"Ramón Urías",
"Richard Fitts",
"Riley O'Brien",
"Ryan Fernandez",
"Ryne Stanek",
"Thomas Saggese",
"Victor Scott II",
"Yohel Pozo"
],
"Tampa Bay Rays": [
"Ben Williamson",
"Bryan Baker",
"Cedric Mullins",
"Chandler Simpson",
"Chris Roycroft",
"Cole Sulser",
"Craig Kimbrel",
"Drew Rasmussen",
"Garrett Cleavinger",
"Griffin Jax",
"Hunter Feduccia",
"Jonathan Aranda",
"Jonny DeLuca",
"Junior Caminero",
"Kevin Kelly",
"Nick Martinez",
"Richie Palacios",
"Ryan Vilade",
"Shane McClanahan",
"Taylor Walls",
"Victor Mesa Jr.",
"Yandy Díaz"
],
"Texas Rangers": [
"Alejandro Osuna",
"Brandon Nimmo",
"Cal Quantrill",
"Chris Martin",
"Cole Winn",
"Elias Díaz",
"Evan Carter",
"Ezequiel Duran",
"Gavin Collyer",
"Jacob Latz",
"Jacob deGrom",
"Jake Burger",
"Joc Pederson",
"Josh Jung",
"Justin Foscue",
"Kumar Rocker",
"Kyle Higashioka",
"MacKenzie Gore",
"Nathan Eovaldi",
"Tyler Alexander",
"Wyatt Langford"
],
"Toronto Blue Jays": [
"Adam Macko",
"Addison Barger",
"Adrián Morejón",
"Alejandro Kirk",
"Alek Jacob",
"Andrés Giménez",
"Anthony Santander",
"Blake Hunt",
"Bowden Francis",
"Bradgley Rodriguez",
"Brandon Valenzuela",
"Braydon Fisher",
"Brendon Little",
"Charles McAdoo",
"Chase Lee",
"Cody Ponce",
"Daulton Varsho",
"David Morgan",
"Davis Schneider",
"Davis Snider",
"Dylan Cease",
"Ernie Clement",
"Fernando Tatis Jr.",
"Freddy Fermín",
"Gavin Sheets",
"George Springer",
"Germán Márquez",
"Griffin Canning",
"JP Sears",
"Jackson Merrill",
"Jake Bloss",
"Jake Cronenworth",
"Jase Bowen",
"Jason Adam",
"Jeff Hoffman",
"Jeremiah Estrada",
"Jesús Sánchez",
"Jhony Brito",
"Joe Mantiply",
"Joe Musgrove",
"Jonatan Clase",
"José Berríos",
"Kazuma Okamoto",
"Kevin Gausman",
"Kyle Hart",
"Lazaro Estrada",
"Lenyn Sosa",
"Louie Varland",
"Louis Varland",
"Lucas Giolito",
"Luis Campusano",
"Luis Rengifo",
"Luis Urías",
"Manny Machado",
"Mason Fluharty",
"Mason Miller",
"Matt Waldron",
"Max Scherzer",
"Michael King",
"Miguel Andújar",
"Myles Straw",
"Nathan Lukes",
"Nick Pivetta",
"Patrick Corbin",
"Ramón Laureano",
"Randy Vásquez",
"Rodolfo Durán",
"Ron Marinaccio",
"Sean Keys",
"Shane Bieber",
"Spencer Miles",
"Sung Mun Song",
"Trey Yesavage",
"Ty France",
"Tyler Rogers",
"Vladimir Guerrero Jr.",
"Walker Buehler",
"Wandy Peralta",
"Will Wagner",
"Willie MacIver",
"Xander Bogaerts",
"Yimi García",
"Yohendrick Pinango",
"Yuki Matsui"
],
"Unsorted": [
"Aaron Judge",
"Adam Frazier",
"Alan Roden",
"Austin Wells",
"Christian Vázquez",
"Christian Walker",
"Francisco Lindor",
"Justin Turner",
"Nick Fortes"
],
"Washington Nationals": [
"Andrés Chaparro",
"CJ Abrams",
"Curtis Mead",
"Dylan Crews",
"Jacob Young",
"James Wood",
"José Tena",
"Justin Lawrence",
"Keibert Ruiz",
"Luis García Jr.",
"Miles Mikolas",
"Nasim Nuñez",
"Orlando Ribalta",
"Tom Cosgrove",
"Zack Littell"
],
"Philadelphia Phillies": [
"Garrett Stubbs"
],
"No active team": [
"Matt Reynolds"
]
},
"songs": {
"Vladimir Guerrero Jr.": "Janice STFU — Drake",
"George Springer": "Pa' Que Retozen — Tego Calderón",
"Alejandro Kirk": "El Mechón — Banda MS",
"Daulton Varsho": "Thunderstruck — AC/DC",
"Ernie Clement": "I Was Made For Lovin' You — KISS",
"Davis Schneider": "Pink Pony Club — Chappell Roan",
"Davis Snider": "Pink Pony Club — Chappell Roan",
"Xander Bogaerts": "X Gon' Give It To Ya — DMX",
"Jackson Merrill": "Da Fonk (feat. Joni) — Mochakk, Joni",
"Jase Bowen": "Awesome God — R-Swift",
"Ramón Laureano": "DÁKITI — Bad Bunny, JHAYCO",
"Will Wagner": "Excavator — Don Toliver",
"Jake Cronenworth": "Keep Their Heads Ringin' — Dr. Dre",
"Luis Campusano": "I'M ON SOME — Gunna",
"Manny Machado": "Otro Trago (Remix) — Sech, Ozuna, Anuel AA, Darell, Nicky Jam",
"Luis Rengifo": "Bo de Bo de Bo — Jey One, Yaisel LM, OG DETRUYELO",
"Fernando Tatis Jr.": "Acábame De Matar — Banda El Recodo",
"Sung Mun Song": "Okey Dokey — MINO, ZICO",
"Ty France": "Good Life — Kanye West, T-Pain",
"Blake Hunt": "Dammit — Alexandra Kay",
"Gavin Sheets": "Hypnotize — The Notorious B.I.G.",
"Michael King": "Messin' with the King — Olivia King, Maye Star",
"Miguel Andújar": "LA MuDANZA — Bad Bunny",
"Freddy Fermín": "Pepas — Farruko",
"Yuki Matsui": "ジェニファー (Jennifer) — Aimyon",
"Walker Buehler": "Bulls On Parade — Rage Against The Machine",
"Griffin Canning": "Texas Sun — Khruangbin, Leon Bridges",
"Mason Miller": "Blind — Korn",
"Nick Pivetta": "Wipe Me Down (Remix) — Trill Family, Boosie Badazz, Webbie, Foxx",
"Germán Márquez": "Pensando En Ti — Dimensión Latina",
"Alek Jacob": "20 Min — Lil Uzi Vert",
"JP Sears": "Baba O'Riley — The Who",
"Jason Adam": "Use This Gospel — Kanye West, Clipse, Kenny G",
"Joe Musgrove": "Vampire (feat. Whiteboy John) — Tribal Seeds",
"Rodolfo Durán": "Ley Seca — JHAYCO, Anuel AA",
"Adrián Morejón": "Rompe — Daddy Yankee",
"Lucas Giolito": "Kickstart My Heart — Mötley Crüe",
"Jeremiah Estrada": "El Rey — Vicente Fernández",
"Wandy Peralta": "Aguanile — Marc Anthony",
"Matt Waldron": "Sugar Wraith — Post Malone",
"David Morgan": "Closer to the Sun — Slightly Stoopid",
"Kyle Hart": "You Broke My Heart — Drake",
"Bradgley Rodriguez": "<3 — Bad Bunny",
"Jhony Brito": "Las Avispas — Juan Luis Guerra 4.40",
"Ron Marinaccio": "We No Speak Americano — Yolanda Be Cool, DCup",
"Randy Vásquez": "Lean On — Major Lazer, DJ Snake, MØ, Diplo",
"Jonatan Clase": "Bandoleros — Don Omar, Tego Calderón",
"Kazuma Okamoto": "Iris — Goo Goo Dolls",
"Luis Urías": "Por Las Calles de Chihuahua — Banda MS",
"Myles Straw": "I Don't Want to Miss a Thing — Aerosmith",
"Nathan Lukes": "Vertigo — U2",
"Spencer Miles": "Miles On It — Marshmello, Kane Brown",
"Shane Bieber": "Real World — Matchbox Twenty",
"Dylan Cease": "Soul Man — The Blues Brothers",
"Patrick Corbin": "Levels — Avicii",
"Braydon Fisher": "Savior — Rise Against",
"Kevin Gausman": "Money - 2023 Remaster — Pink Floyd",
"Jeff Hoffman": "Alive (nightmare) — Kid Cudi, Ratatat",
"Adam Macko": "Return of the Mack — Mark Morrison",
"Tyler Rogers": "Ain't No Rest for the Wicked — Cage The Elephant",
"Louis Varland": "Animal I Have Become — Three Days Grace",
"Trey Yesavage": "Cowboy — Kid Rock",
"Jake Bauers": "California Soul — Marlena Shaw",
"William Contreras": "Not Like Us — Kendrick Lamar",
"Sal Frelick": "Slow Down — Clyde Carson",
"Garrett Mitchell": "Niagara Falls (Foot or 2) — Metro Boomin",
"Joey Ortiz": "Awesome God — R-Swift",
"Cooper Pratt": "The Devil Went Down to Georgia — The Charlie Daniels Band",
"Gary Sánchez": "La Gozadera — Gente De Zona",
"Brice Turang": "Alive — P.O.D.",
"Andrew Vaughn": "God's Gonna Cut You Down — Johnny Cash",
"Robert Gasser": "Believe — The Bravery",
"Jared Koenig": "Loud and Heavy — Cody Jinks",
"Trevor Megill": "The Four Horsemen — Metallica",
"Jacob Misiorowski": "I Came To Play — WWE / Downstait",
"Chad Patrick": "I Wrote The Book — Morgan Wallen",
"Abner Uribe": "HAY LUPITA — Lomiiel",
"Bryse Wilson": "Ain't No Love In Oklahoma — Luke Combs",
"Henry Davis": "Free Bird — Lynyrd Skynyrd",
"Mitch Keller": "The Thrill — Wiz Khalifa & Empire Of The Sun",
"Brandon Lowe": "I Love This Life — LOCASH",
"Jake Mangum": "Your Love — The Outfield",
"Carmen Mlodzinski": "Highway Chile — Jimi Hendrix",
"Mason Montgomery": "Thunderstruck — AC/DC",
"Ryan O'Hearn": "Stranglehold — Ted Nugent",
"Marcell Ozuna": "Kick Con El Bajo — Tivi Gunz",
"Bryan Reynolds": "Beer For My Horses — Toby Keith",
"Gregory Soto": "Etel — Mestizo Is Back & Puyalo Pantera",
"Jared Triolo": "Sweetness — Jimmy Eat World",
"Mookie Betts": "Soul Survivor — Jeezy, Akon",
"Alex Call": "I'm So Blessed — CAIN",
"Tommy Edman": "Stay — Zedd, Alessia Cara",
"Freddie Freeman": "Baila Conmigo (feat. Kelly Ruiz) — Dayvi, Victor Cardenas, Kelly Ruíz",
"Teoscar Hernández": "OHNANA — Kapo",
"Landon Knack": "Return of the Mack — Mark Morrison",
"Max Muncy": "Cowgirl — Shaboozey",
"Emmet Sheehan": "God's Gonna Cut You Down — Johnny Cash",
"Kyle Tucker": "Walk Thru (feat. Problem) — Rich Homie Quan",
"Alex Vesia": "Gasoline — Seether",
"Yoshinobu Yamamoto": "Frontier (Extended Mix) — VINAI, SCNDL",
"Vaughn Grissom": "Could You Be Loved — Bob Marley & The Wailers",
"Tyler Heineman": "Edge of Seventeen — Stevie Nicks",
"Josh Lowe": "No Place — RÜFÜS DU SOL",
"Wade Meckler": "Hussle & Motivate — Nipsey Hussle",
"Zach Neto": "Big Poppa — The Notorious B.I.G.",
"Oswald Peraza": "Neverita — Bad Bunny",
"Grayson Rodriguez": "Texas — BigXthaPlug",
"Jose Siri": "Bing Bong — Yailin la Mas Viral & Puyalo Pantera",
"Jorge Soler": "PARA SIEMPRE — Daddy Yankee",
"Brent Suter": "Too Legit To Quit — MC Hammer",
"Mike Trout": "Super Gremlin — Kodak Black",
"Kirby Yates": "Could You Be Loved — Bob Marley & The Wailers",
"Josh Bell": "Hip-Hop (Instrumental) — Dead Prez",
"Taj Bradley": "Feeling — LADIPOE",
"Victor Caratini": "Agradecido — Don Omar",
"Kody Clemens": "Cooped Up — Post Malone & Mark Morrison",
"Kody Funderburk": "Thunderstruck — AC/DC",
"Yoendrys Gómez": "Punto Y Aparte",
"Tristan Gray": "Never Get Used To This — Forrest Frank & JVKE",
"Alex Jackson": "Waiting For Never — Post Malone",
"Ryan Jeffers": "Duffle Bag Boy — Playaz Circle",
"Luke Keaschall": "Buzzin — Mann",
"Ryan Kreidler": "Disciples — Tame Impala",
"Trevor Larnach": "You Know How We Do It — Ice Cube",
"Brooks Lee": "Love Tonight — Shouse",
"Royce Lewis": "I Know — Big Sean",
"Austin Martin": "Edge of Desire — Jonas Blue & Malive",
"Zebby Matthews": "Bad Company — Five Finger Death Punch",
"Andrew Morris": "Smells Like Teen Spirit — Nirvana",
"Tommy Nance": "Ain't No Grave — Johnny Cash",
"Bailey Ober": "Immigrant Song — Led Zeppelin",
"Mike Paredes": "Let It Happen — Tame Impala",
"Taylor Rogers": "The Chain — Fleetwood Mac",
"Kendry Rojas": "La Vida Es Un Carnaval — Celia Cruz",
"Joe Ryan": "Long Cool Woman (In a Black Dress) — The Hollies",
"Lawrence Butler": "On One Tonight — Gunna",
"Aaron Civale": "Black Betty — Ram Jam",
"Jonah Heim": "It's About Time — Russell Dickerson",
"Shea Langeliers": "Ride Wit Me — Nelly · City Spud",
"Mark Leiter Jr.": "The Mountain — Dierks Bentley",
"Jacob Lopez": "Friends In Low Places — Garth Brooks",
"Jeff McNeil": "Rock Of Ages — Def Leppard",
"Joey Meneses": "Cada Quien — Grupo Firme & Maluma",
"Tyler Soderstrom": "Rocketeer — Far East Movement",
"Jeffrey Springs": "No Diggity — Blackstreet · Dr. Dre · Queen Pen",
"Alika Williams": "Doin' Time — Sublime",
"Luisangel Acuña": "ACHO PR — Bad Bunny",
"Andrew Benintendi": "Encantadora — Yandel",
"Erick Fedde": "Bullet With Butterfly Wings — The Smashing Pumpkins",
"Randal Grichuk": "Home — Good Neighbours",
"Jordan Hicks": "GTA — Future & Metro Boomin",
"Chris Murphy": "War Pigs — Black Sabbath",
"Sean Newcomb": "Lose My Mind — Jeezy",
"Miguel Vargas": "Todo Está Ok — Fixty Ordara y Ja Rulay",
"Brennan Bernardino": "That's How I Knew — Nipsey Hussle",
"Willi Castro": "Porón Pompón — Crazy Design",
"Tyler Freeman": "Cowgirls — Morgan Wallen",
"Edouard Julien": "All My Life — Lil Durk & J. Cole",
"Michael Lorenzen": "Siren — The Movement",
"Jake McCarthy": "WWE: Medal (Kurt Angle) — Jim Johnston",
"Jordan Romano": "Tsunami — DVBBS & Borgeous",
"Christian Yelich": "Jungle — Andre Nickatina",
"Jacob Wilson": "Your Love — The Outfield",
"Luis Arraez": "HAY LUPITA — Lomiiel",
"Spencer Bivens": "Made You Look — Nas",
"Bryce Eldridge": "By Your Grace — Cody Johnson",
"Sam Hentges": "Break Em' Off — Paul Wall",
"Adrian Houser": "Run Through The Jungle — Creedence Clearwater Revival",
"Christian Koss": "Twerkulator — City Girls",
"Jung Hoo Lee": "Dang Dang Dang — Supreme Team",
"Tyler Mahle": "Rooster — Alice In Chains",
"Grant McCray": "On One Tonight — Gunna",
"Robbie Ray": "Burn It Down — Warren Zeiders",
"Landen Roupp": "Sleeping on the Blacktop — Colter Wall",
"Casey Schmitt": "Hot (Remix) — Young Thug, Gunna & Travis Scott",
"Keaton Winn": "Keep Your Hands to Yourself — The Georgia Satellites",
"David Bednar": "Renegade — Styx",
"Paul Blackburn": "WHO? WHAT! — Travis Scott",
"José Caballero": "Bailando en la Lluvia — Daddy Yankee",
"Gerrit Cole": "Lean Back — Terror Squad",
"Fernando Cruz": "Circle of Life — The Lion King",
"Camilo Doval": "El Hijo Desobediente — Antonio Aguilar",
"Paul Goldschmidt": "Grave Robber — Crowder",
"Trent Grisham": "No Longer Bound (I'm Free) — Maverick City Music & Forrest Frank",
"Amed Rosario": "Elly De La Cruz — T.Y.S",
"Max Schuemann": "Self-Made — Bryson Tiller",
"Anthony Volpe": "Where You Are — John Summit & Hayla",
"Ryan Weathers": "Night Shift — Jon Pardi",
"CJ Abrams": "36 Oz. — Skeme",
"Andrés Chaparro": "Fabricando Fantasías",
"Tom Cosgrove": "Otis — JAY-Z & Kanye West",
"Dylan Crews": "I Bet U Won't — Mouse and Level",
"Luis García Jr.": "Esa Muchacha — Los Hermanos Rosario",
"Justin Lawrence": "Soul Survivor — Jeezy",
"Zack Littell": "Money for Nothing — Dire Straits",
"Curtis Mead": "Holdin On — Flume",
"Miles Mikolas": "Mississippi Queen — Mountain",
"Nasim Nuñez": "Hustler Musik — Lil Wayne",
"Orlando Ribalta": "Silencio — Velito el Bufón",
"Keibert Ruiz": "LA RANGER — The Academy & Myke Towers",
"José Tena": "Dale Gracias Al Señor — Joe Arroyo",
"James Wood": "Me, Myself and I — Beyoncé",
"Jacob Young": "Young Forever — JAY-Z",
"Wilyer Abreu": "Sentir Zuliano — Cardenales Del Exito",
"Aroldis Chapman": "La Vida Es Un Carnaval — Celia Cruz",
"Danny Coulombe": "What An Awesome God — Phil Wickham",
"Jarren Duran": "Pound Cake / Paris Morton Music 2 — Drake · JAY-Z",
"Caleb Durbin": "Alive (nightmare) — Kid Cudi · Ratatat",
"Sonny Gray": "Throwback (feat. Chris Brown) — B.o.B · Chris Brown",
"Andruw Monasterio": "El Duro — Don Omar · Kendo Kapponi",
"Jovani Morán": "JOVEN LEYENDA — Myke Towers",
"Carlos Narváez": "Heartless — Kanye West",
"Ceddanne Rafaela": "Quienes Son Ustedes — Eladio Carrion",
"Anthony Seigler": "Hey Ya! — Outkast",
"Justin Slaten": "The Chain - 2004 Remaster — Fleetwood Mac",
"Payton Tolle": "Lonely Is The Night - Remastered 2010 — Billy Squier",
"Ryan Watson": "Frogman — Whiskey Myers",
"Greg Weissert": "Chill Bill (feat. J. Davi$ & Spooks) — Rob $tone · J. Davi$ · J Spooks",
"Garrett Whitlock": "Bury Me in Georgia — Kane Brown",
"Connor Wong": "Wanna Be A Baller - Album Version (Edited) — Lil' Troy",
"Masataka Yoshida": "Touch The Sky — Kanye West · Lupe Fiasco",
"Francisco Alvarez": "MOLI — El Alfa",
"Bo Bichette": "tv off — Kendrick Lamar",
"Xzavion Curry": "PUFFIN ON ZOOTIEZ — Future",
"Sean Manaea": "Just the Two of Us — Grover Washington Jr.",
"A.J. Minter": "Halftime (Stand Up and Get Crunk!) — Ying Yang Twins",
"Tobias Myers": "Livin' It Up — Ja Rule",
"Freddy Peralta": "Simplemente Gracias — Ala Jaza",
"Jorge Polanco": "Nunca Creyeron — Wilmer Roberts",
"Brooks Raley": "Loud and Heavy — Cody Jinks",
"Christian Scott": "Everyday Hustle — Future & Metro Boomin",
"Kodai Senga": "Tokyo Drift — Teriyaki Boyz",
"Juan Soto": "EoO — Bad Bunny",
"Tyrone Taylor": "Like Whaaat (feat. Wiz Khalifa, Tyga, Chris Brown & Master P) - Remix — JasonMartin · Wiz Khalifa · Tyga · Chris Brown · Master P",
"Luis Torrens": "Qué Pasaría... — Rauw Alejandro & Bad Bunny",
"Eric Wagaman": "Alive (Nightmare) — Kid Cudi",
"Devin Williams": "From Nothing — Key Glock",
"Jared Young": "Young Forever — JAY-Z",
"Eduard Bazardo": "Capaz (Merengueton) — Alleh & Yorghaki",
"Dominic Canzone": "Hopeless Romantic — Wiz Khalifa",
"Luis Castillo": "Que Calor — Major Lazer",
"J.P. Crawford": "Around the World — Fortunate Youth & Mellow Mood",
"José A. Ferrer": "Mango Piña — Braulio Fogon",
"Mitch Garver": "Enemies — Post Malone",
"Logan Gilbert": "Gangsta's Paradise — Coolio",
"Emerson Hancock": "They Don't Know — Jason Aldean",
"George Kirby": "Survive — Space Laces",
"Bryce Miller": "Bury My Bones — Whiskey Myers",
"Andrés Muñoz": "Pepas (David Guetta Remix) — Farruko & David Guetta",
"Josh Naylor": "Stan — Eminem",
"Cal Raleigh": "Bad Luck — Zach Top",
"Luke Raley": "Boys Back Home — Dylan Marlowe & Dylan Scott",
"Victor Robles": "La Chiflera Que Palomo! — Daniel Galan",
"Gabe Speier": "No Good — KALEO",
"Weston Wilson": "Nevermind — Dennis Lloyd",
"Bryan Woo": "The Woo — Pop Smoke",
"Cole Young": "Too Many Nights — Metro Boomin",
"Jonathan Aranda": "En Privado — Xavi & Manuel Turizo",
"Bryan Baker": "Levels — Avicii",
"Junior Caminero": "Lakenoshi — Omar Courtz",
"Garrett Cleavinger": "Another Day in Paradise — Quinn XCII",
"Jonny DeLuca": "Candy — Mk.gee",
"Yandy Díaz": "Pa' Los Envidiosos — Pitbull & Lenier",
"Hunter Feduccia": "Hate It Or Love It — The Game",
"Griffin Jax": "The Needle And The Spoon — Lynyrd Skynyrd",
"Kevin Kelly": "All The Small Things — blink-182",
"Craig Kimbrel": "Like a Prayer — Josh Fawaz",
"Nick Martinez": "Baianá — Bakermat",
"Shane McClanahan": "Stairway to Heaven — Led Zeppelin",
"Victor Mesa Jr.": "Mi Nombre — Bebeshito",
"Cedric Mullins": "WE ON GO — BIA",
"Richie Palacios": "WALK — Hulvey & Lecrae",
"Drew Rasmussen": "In Bloom — Nirvana",
"Chris Roycroft": "Check My Brain — Alice In Chains",
"Chandler Simpson": "Sum 2 Prove — Lil Baby",
"Cole Sulser": "The Chain — Fleetwood Mac",
"Ryan Vilade": "Unwritten — Natasha Bedingfield",
"Taylor Walls": "Get Low — Lil Jon & The East Side Boyz",
"Ben Williamson": "Houston, We Got a Problem — Luke Combs",
"Gabriel Arias": "DIOS HA SIDO BUENO — Madiel Lara",
"Shawn Armstrong": "God's Gonna Cut You Down — Johnny Cash",
"Patrick Bailey": "UP! — Forrest Frank & Connor Price",
"Tanner Bibee": "wacced out murals — Kendrick Lamar",
"Joey Cantillo": "Ezekiel — Sons of Yeshua",
"Slade Cecconi": "Lord Pretty Flacko Jodye 2 (LPFJ2) — A$AP Rocky",
"David Fry": "Loud and Heavy — Cody Jinks",
"Hunter Gaddis": "Hoist The Colours (TT Mix) — Nomit",
"Austin Hedges": "I'm Gonna Be — Post Malone",
"Colin Holderman": "Soul Survivor — Jeezy",
"Rhys Hoskins": "Consideration — Rihanna",
"Kyle Manzardo": "Drifter — Hippie Sabotage",
"Brayan Rocchio": "PA QUE LO BAILES (BAILALO ROCKY) — Lomiiel",
"Daniel Schneemann": "Let It All Work Out — Lil Wayne",
"Cade Smith": "Fire It Up — Thousand Foot Krutch",
"Gavin Williams": "Collie Herb Man — Katchafire",
"Sandy Alcantara": "Subimos de Rango — Bad Bunny, Omy de Oro & Shootter Ledo",
"Griffin Conine": "Tokyo Drifting — Glass Animals",
"Xavier Edwards": "SKITZO — Travis Scott",
"Pete Fairbanks": "Anthem Part Two — blink-182",
"Ryan Gusto": "We Takin' Over — DJ Khaled",
"Heriberto Hernández": "Jordan — Rochy RD",
"Liam Hicks": "Your Soul — Hippie Sabotage",
"Leo Jiménez": "Levitating — Dua Lipa",
"Janson Junk": "Wheel in the Sky — Journey",
"Otto Lopez": "Bing Bong — Yailin la Mas Viral & Puyalo Pantera",
"Eury Pérez": "Tu No Vive Asi — Arcángel & Bad Bunny",
"Tyler Phillips": "Blue Notes — Meek Mill",
"Esteury Ruiz": "La Copa — Don Omar",
"Javier Sanoja": "Una Chica Good Good — DembowBeatz",
"Kyle Stowers": "COUNT 'EM — Brandon Lake",
"Derek Hill": "Rich Off Rap — BigXthaPlug",
"Brad Keller": "Whatever It Takes — Imagine Dragons",
"Tim Mayza": "Remember When — Chevelle",
"Drew Anderson": "Fat Bottomed Girls — Queen",
"Beau Brieske": "Feeling Good — Nina Simone",
"Kerry Carpenter": "This Is My Song — North Point Worship",
"Dillon Dingler": "Edge of Seventeen — Stevie Nicks",
"Kyle Finnegan": "Safari Song — Greta Van Fleet",
"Jack Flaherty": "Jungle — X Ambassadors",
"Riley Greene": "1, 2 Step — Ciara",
"Tyler Holton": "Everybody Wants To Rule The World — Tears For Fears",
"Kenley Jansen": "In the Stone — Earth, Wind & Fire",
"Colt Keith": "Cowboy — Kid Rock",
"Hao-Yu Lee": "Pound Cake — Drake",
"Kevin McGonigle": "Could You Be Loved — Bob Marley & The Wailers",
"Zach McKinstry": "Shine — Collective Soul",
"Casey Mize": "Ladders — Mac Miller",
"Keider Montero": "Dios Te Bendiga — Arcángel",
"James Outman": "Soleil Bleu — Bleu Soleil & LUIZA",
"Jake Rogers": "Rodeo — Garth Brooks Tribute",
"Tarik Skubal": "Holy Grail — JAY-Z",
"Spencer Torkelson": "The Way I Are — Timbaland",
"Framber Valdez": "Creere — Tercer Cielo",
"Matt Vierling": "Where You Are — John Summit & Hayla",
"Jacob Waguespack": "Adios — Trill Family",
"Luinder Avila": "ACHO PR — Bad Bunny",
"Jac Caglianone": "Solo — Future",
"Noah Cameron": "Unstoppable — The Score",
"Isaac Collins": "Neverender (Kaytranada Remix) — Justice & Tame Impala",
"Steven Cruz": "Abayarde — Tego Calderón",
"Lucas Erceg": "Bamboo — E-40",
"Carter Jensen": "B's On The Table — Drake",
"Alex Lange": "Sweet Emotion — Aerosmith",
"Nick Loftin": "Say It (Illenium Remix) — Flume & ILLENIUM",
"Seth Lugo": "Angry Again — Megadeth",
"Daniel Lynch IV": "Someone To Love — Stephen Marley",
"Luke Maile": "Kashmir — Led Zeppelin",
"Starling Marte": "Bo de Bo de Bo — Jey One, Yaisel LM & OG DETRUYELO",
"Michael Massey": "Mr. Brightside — The Killers",
"Eli Morgan": "Can't You Hear Me Knocking — The Rolling Stones",
"Vinnie Pasquantino": "White Iverson — Post Malone",
"Salvador Perez": "100 MILLONES — Bad Bunny & Luar La L",
"Josh Rojas": "Rolling in the Deep — Adele",
"John Schreiber": "The Chain — Fleetwood Mac",
"Matt Strahm": "How Bad Do You Want It — Tim McGraw",
"Lane Thomas": "What I Want — Morgan Wallen",
"Tyler Tolbert": "I Luv It — Jeezy",
"Bobby Witt Jr.": "The Less I Know The Better — Tame Impala",
"Samuel Basallo": "Misericordia — Onell Diaz · Farruko",
"Shane Baz": "Rooster (2022 Remaster) — Alice In Chains",
"Dylan Beavers": "Overdue (with Travis Scott) — Metro Boomin · Travis Scott",
"Kyle Bradish": "Memories (feat. Kid Cudi) — David Guetta · Kid Cudi",
"Yennier Cano": "Como Te Pago — Lenier",
"Rico Garcia": "Vampire — Tribal Seeds",
"Gunnar Henderson": "The Sweet Escape — Gwen Stefani · Akon",
"Jackson Holliday": "Mr. Blue Sky — Electric Light Orchestra",
"Jeremiah Jackson": "Revolution — Kirk Franklin & The Family",
"Andrew Kittredge": "Crimson and Clover — Joan Jett & the Blackhearts",
"Coby Mayo": "AT THE PARTY (feat. Pharrell Williams, Travis Scott) — Kid Cudi · Pharrell Williams · Travis Scott",
"Anthony Nunez": "WALK — Hulvey · Lecrae",
"Tyler O'Neill": "The Motto — Drake · Lil Wayne",
"Trevor Rogers": "Sharp Dressed Man (2008 Remaster) — ZZ Top",
"Albert Suárez": "Danza Kuduro — Don Omar · Lucenzo",
"Leody Taveras": "Las Avispas — Juan Luis Guerra 4.40",
"Taylor Ward": "Superhero (Heroes & Villains) — Metro Boomin",
"Tyler Wells": "Waiting for the Thunder — Blackberry Smoke",
"Grant Wolfram": "Outlaw State Of Mind — Chris Stapleton",
"Brandon Young": "Cold — Crossfade",
"Bryan Abreu": "Abatido — Farruko & Makaco el Cerebro",
"Nick Allen": "Next to You — Mike Jones",
"Jose Altuve": "Volver — Piso 21, Marc Anthony & Beéle",
"Yordan Alvarez": "Demasiado — Gente De Zona",
"Spencer Arrighetti": "God Is — Kanye West",
"AJ Blubaugh": "Gonna Fly Now — Bill Conti",
"Hunter Brown": "Just What the Doctor Ordered — Ted Nugent",
"Zach Dezenzo": "Ms. Jackson — Outkast",
"Yainer Diaz": "ACHO PR — Bad Bunny",
"Josh Hader": "Fireman — Lil Wayne",
"Tatsuya Imai": "Let's Get Ridiculous — Redfoo",
"Cristian Javier": "El Trote — Rochy RD & Yanco Bars",
"Bryan King": "Dance Now — JID",
"Peter Lambert": "Up Down — Morgan Wallen",
"Brice Matthews": "pick up the phone — Travis Scott",
"Steven Okert": "Kings of Summer — ayokay & Quinn XCII",
"Isaac Paredes": "Jefe De Jefes — Los Tigres Del Norte",
"Nate Pearson": "White Horse — Chris Stapleton",
"Jeremy Peña": "My Chick Bad — Ludacris",
"Cam Smith": "Lose My Mind — Jeezy",
"Taylor Trammell": "Hermeneutics — Caleb Gordon",
"LaMonte Wade Jr.": "Plenty Money — Plies",
"Tyler Alexander": "Tom Sawyer — Rush",
"Jake Burger": "Back On My BS — BigXthaPlug",
"Evan Carter": "Jesus Walks — Kanye West",
"Gavin Collyer": "Let's Go — Key Glock",
"Jacob deGrom": "Simple Man — Lynyrd Skynyrd",
"Elias Díaz": "Como Te Pago — Lenier",
"Ezequiel Duran": "MLQHD — Alex Zurdo, Funky & Redimi2",
"Nathan Eovaldi": "Come Together — Gary Clark Jr. & Junkie XL",
"MacKenzie Gore": "Crooked Smile — J. Cole",
"Kyle Higashioka": "Just Got Paid — ZZ Top",
"Josh Jung": "Turn This Truck Around — Jordan Davis",
"Wyatt Langford": "Lord Of All — Crowder",
"Jacob Latz": "Mass Appeal — Gang Starr",
"Chris Martin": "Texas — BigXthaPlug",
"Brandon Nimmo": "I'm So Blessed — CAIN",
"Alejandro Osuna": "Por Mi México — Lefty Sm & Santa Fe Klan",
"Joc Pederson": "Hell & Back — Kid Ink",
"Cal Quantrill": "Famous Last Words — My Chemical Romance",
"Kumar Rocker": "That's On Me — Yella Beezy",
"Cole Winn": "Heads Will Roll (A-Trak Remix) — Yeah Yeah Yeahs",
"Kevin Alcántara": "Opr — Gesaffelstein",
"Miguel Amaya": "Panama - 2015 Remaster — Van Halen",
"Javier Assad": "Gracias - En Vivo — Grupo Firme · Grupo Codiciado",
"Matthew Boyd": "Voodoo Child (Slight Return) — Jimi Hendrix",
"Alex Bregman": "Revival — Zach Bryan",
"Michael Busch": "If I Can't - Album Version (Edited) — 50 Cent",
"Michael Conforto": "Blink Twice — Shaboozey · Myles Smith",
"Pete Crow-Armstrong": "End of Beginning — Djo",
"Ian Happ": "Spectrum (Say My Name) — Xd",
"Nico Hoerner": "whoa (mind in awe) — XXXTENTACION",
"Gavin Hollowell": "Devil Eyes — Hippie Sabotage",
"Shota Imanaga": "Chelsea Dagger — The Fratellis",
"Carson Kelly": "Take Me Home Tonight — Eddie Money",
"Phil Maton": "Under Pressure — Logic",
"David Peterson": "Simple Man — Lynyrd Skynyrd",
"Colin Rea": "red (feat. Morgan Wallen) — HARDY · Morgan Wallen",
"Seiya Suzuki": "My Way - 2008 Remastered — Frank Sinatra",
"Dansby Swanson": "Shabang — Drake",
"Caleb Thielbar": "Wake Up — Rage Against The Machine",
"Jacob Webb": "Have a Drink on Me — AC/DC",
"Andrew Abbott": "God's Country — Blake Shelton",
"Tejay Antone": "Blah Blah Blah — Armin van Buuren",
"JJ Bleday": "Magic Man — Heart",
"Brock Burke": "Square Dance — Eminem",
"Elly De La Cruz": "Elly De La Cruz — Johny Locus",
"Hunter Greene": "Public Service Announcement (Interlude) — JAY-Z",
"Ke'Bryan Hayes": "What You Saying — Lil Uzi Vert",
"Pierce Johnson": "The Purge Siren Dubstep — Macpro",
"Nick Lodolo": "Save a Horse (Ride a Cowboy) — Big & Rich",
"Nathaniel Lowe": "Life Is Good — Future, Drake",
"Noelvi Marte": "Socorro — Jey One",
"Sam Moll": "WWE: Locked In (Trick Williams) — def rebel",
"Emilio Pagán": "Kingdom — Downstait",
"Brady Singer": "Waiting for the Thunder — Blackberry Smoke",
"Spencer Steer": "Shiver — John Summit, HAYLA",
"Tyler Stephenson": "All My Life — Lil Durk, J. Cole",
"Eugenio Suárez": "Sonríele — Daddy Yankee",
"Jose Trevino": "Hip Hop Hooray — Naughty By Nature",
"Ozzie Albies": "PARANOIA — Jonna Fraser, Yung Felix",
"Joey Bart": "Chasin' That Neon Rainbow — Alan Jackson",
"Dylan Dodd": "Lonely Is The Night — Billy Squier",
"Mauricio Dubón": "Ganas De Ti — Arcángel",
"Bryce Elder": "Time of Day — Turnpike Troubadours",
"Kyle Farmer": "Still Goin Down — Morgan Wallen",
"Michael Harris II": "Viking — SahBabii",
"Brewer Hicklen": "Tremble - Live — Mosaic MSC",
"Grant Holmes": "Welcome 'Round Here — The Marcus King Band",
"Raisel Iglesias": "Not Like Us — Kendrick Lamar",
"Dylan Lee": "Long Cool Woman (In a Black Dress) — The Hollies",
"Reynaldo López": "Halloween Theme — John Carpenter · Cody Carpenter · Daniel Davies",
"Jorge Mateo": "NUEVAYoL — Bad Bunny",
"Matt Olson": "Hell At Night (feat. Ella Langley) — BigXthaPlug",
"Austin Riley": "What You Know — T.I.",
"Chris Sale": "Throw It Up — Lil Jon & The East Side Boyz, Pastor Troy",
"Dominic Smith": "ILoveUIHateU — Playboi Carti",
"Eli White": "Twice As Hard — The Black Crowes",
"Danny Young": "Forever Young — Alphaville",
"Justin Bruihl": "Kickstart My Heart — Mötley Crüe",
"Alec Burleson": "Party Like A Rock Star — Shop Boyz",
"Nathan Church": "Graves Into Gardens (Live) — Elevation Worship",
"Jimmy Crooks": "News or Something — Future",
"José Fermín": "MONACO — Bad Bunny",
"Gordon Graceffo": "Square Dance — Eminem",
"Iván Herrera": "El Hokage — Eladio Carrion",
"Blaze Jordan": "Last Night — Morgan Wallen",
"Kyle Leahy": "On Top — Flume, T-Shirt",
"Matthew Liberatore": "Legend — The Score",
"Dustin May": "Back In Black — AC/DC",
"Michael McGreevy": "Danger Zone — Kenny Loggins",
"Lars Nootbaar": "Brighter — RÜFÜS DU SOL",
"Riley O'Brien": "Spicy — Nas, Fivio Foreign, A$AP Ferg",
"Pedro Pagés": "Change Me — BigXthaPlug",
"Andre Pallante": "What I Can't Put Down — Jon Pardi",
"JoJo Romero": "Suavemente — Elvis Crespo",
"George Soriano": "ABBA PADRE — Madiel Lara",
"Ryne Stanek": "Still D.R.E. (Instrumental) — Dr. Dre",
"Bryan Torres": "I Want It That Way — Backstreet Boys",
"Nelson Velázquez": "Uva Bombom — Rochy RD",
"Jordan Walker": "Feed Tha Streets 2 (Intro) — Roddy Ricch",
"JJ Wetherholt": "BRING HEAVEN DOWN — Hulvey",
"Masyn Winn": "Dirty Diana — Michael Jackson",
"Nolan Arenado": "TOO COOL TO BE CARELESS — PAWSA",
"Jorge Barrosa": "I Adore You (feat. Daecolm) — HUGEL · Topic · Arash · Daecolm",
"Corbin Carroll": "E85 — Don Toliver",
"Taylor Clarke": "Seven Nation Army — The White Stripes",
"Zac Gallen": "Let The Beat Build - Album Version (Edited) — Lil Wayne",
"Kevin Ginkel": "The Pretender — Foo Fighters",
"Merrill Kelly": "Under Ground Kings — Drake",
"Ketel Marte": "PANTI Y COLALE 2.0 — El Alfa · De La Ghetto · Zion · DJ Chulo NYC · El Cherry Scom · La Greña · Ronny GTA · Ezzy R",
"James McCann": "El Campeón — El Kimiko y Yordy · Michel Boutic · EL YORDY DK",
"Gabriel Moreno": "Taboo — Don Omar",
"Geraldo Perdomo": "El Mejor - Remix — Yeison Jimenez · Chayín Rubio",
"Brandon Pfaadt": "Intro — The xx",
"Eduardo Rodriguez": "Jamaican (Bam Bam) — HUGEL · SOLTO (FR)",
"Paul Sewald": "Jump Around — House Of Pain",
"Tim Tawa": "Remember the Name (feat. Styles of Beyond) — Fort Minor · Styles Of Beyond",
"Ryan Thompson": "Praise Him Forever — Jervis Campbell",
"Ildemaro Vargas": "Oh Yeah — Yello",
"Shohei Ohtani": "The Show Goes On — Lupe Fiasco",
"Francisco Lindor": "My Girl — The Temptations",
"Aaron Judge": "Swag Surfin' — Fast Life Yungstaz",
"Pete Alonso": "Money for Nothing — Dire Straits",
"Austin Wells": "Whole Lotta Love — Led Zeppelin",
"Justin Turner": "Top Gun Anthem — Faltermeyer & Stevens",
"Christian Vázquez": "Las Avispas — Juan Luis Guerra 4.40",
"Christian Walker": "UP! — Forrest Frank & Connor Price",
"Nick Fortes": "Choices (Yup) — E-40",
"Alan Roden": "Say You Love Me — Fleetwood Mac",
"Adam Frazier": "Pony",
"Adley Rutschman": "Alive (nightmare) - Album Version (Edited) — Kid Cudi · Ratatat",
"Alek Thomas": "Dile — Don Omar",
"Hyeseong Kim": "ほうき星 (Comet) — Younha",
"Enrique Hernández": "Money En Mi Mente — Eladio Carrión",
"Will Smith": "La La Land — Bryce Vine",
"Andy Pages": "TODO LLEGA A SU TIEMPO — Batallando Con Fé",
"Ryan Ward": "I Love This Life — LOCASH",
"Dalton Rushing": "Mr. Rager — Kid Cudi",
"Miguel Rojas": "Ayer Hablé con Dios (Remix) — Corridos del Rey, Farruko",
"Alex Freeland": "WHO? WHAT! — Travis Scott",
"Edwin Díaz": "Narco — Blasterjaxx, Timmy Trumpet",
"Blake Snell": "tv off (feat. Lefty Gunplay) — Kendrick Lamar",
"Roki Sasaki": "Bailalo Rocky — DJ Roderick",
"Bobby Miller": "Last Breath — Future",
"Tyler Glasnow": "Dazed and Confused (1990 Remaster) — Led Zeppelin",
"Eric Lauer": "Green Gucci Suit (feat. Future) — Rick Ross",
"Gavin Stone": "Photograph — Def Leppard",
"Brock Stewart": "Man in the Box — Alice In Chains",
"Brusdar Graterol": "RIP (Rest In Peace) — Uli Lenz",
"Blake Treinen": "The Outsiders — Eric Church",
"Evan Phillips": "Show Me How to Live — Audioslave",
"Edgardo Henriquez": "VIDRARO EM VOCE — DJ Oma",
"Will Klein": "I'm Shipping Up To Boston — Dropkick Murphys",
"Chayce McDermott": "Borrowed Time — Sam Barber",
"Kyle Hurt": "What Is Love (7″ Mix) — Haddaway",
"Tanner Scott": "Mother — Danzig",
"Justin Wrobleski": "Swing My Way — Offset",
"River Ryan": "God's Country — Blake Shelton",
"Ben Casparius": "Boys Don't Cry — Lil Tecca",
"Jack Dreyer": "One Last Breath (Remix) — ATLiens",
"Jake Cousins": "The Show Goes On — Lupe Fiasco",
"Ha-Seong Kim": "HER — Block B",
"Sean Murphy": "Sittin' Sidewayz (feat. Big Pokey) — Paul Wall",
"Ronald Acuña Jr.": "FANTASMA | AVC — Tainy, JHAYCO",
"Mike Yastrzemski": "When the Levee Breaks — Led Zeppelin",
"Nacho Alvarez Jr.": "back in the a — Gunna",
"Drake Baldwin": "ABC — The Jackson 5",
"AJ Smith-Shawver": "Hey Ya! — Outkast",
"Martín Pérez": "Mi Querencia — Gilberto Santa Rosa",
"Joey Wentz": "Be (Intro) — Common",
"Tyler Kinley": "Voodoo Child (Slight Return) — Jimi Hendrix",
"Spencer Schwellenbach": "Hit This Hard — Post Malone",
"JR Ritchie": "Everlong — Foo Fighters",
"Anthony Molina": "EoO — Bad Bunny",
"Hurston Waldrep": "I Won't Back Down — Tom Petty",
"Connor Thomas": "Nice For What — Drake",
"Jim Jarvis": "Best Love Song — T-Pain",
"Robert Suarez": "Bandoleros — Don Omar · Tego Calderón",
"Joe Jiménez": "Runnin — 21 Savage · Metro Boomin",
"Spencer Strider": "Right Hand On My Heart — The Whigs",
"DaShawn Keirsey Jr.": "NEVER GET USED TO THIS (with JVKE) — Forrest Frank · JVKE",
"James Karinchak": "The Politics & The Life — Daniel Pemberton · Gareth Williams",
"Victor Scott II": "Let's Do It — Lil Baby, Playboi Carti, Skooly",
"Nolan Gorman": "No Hands — Waka Flocka Flame",
"Thomas Saggese": "Sweet Dreams — Eurythmics",
"Ramón Urías": "Bandida — Luis R Conriquez, Peso Pluma",
"César Prieto": "DtMF — Bad Bunny",
"Richard Fitts": "Bright Lights Bigger City — CeeLo Green",
"Hunter Dobbins": "Bloody Nails — Joe Bryson",
"Matt Svanson": "Just a Friend — Biz Markie",
"Yohel Pozo": "capaz (merengueton) — Alleh · Yorghaki",
"Ryan Fernandez": "A Mis Abuelos — Arturo Sandoval",
"Jesús Sánchez": "Creere — Tercer Cielo",
"José Berríos": "TIEMPOS BUENOS — Farruko, Madiel Lara",
"Sean Keys": "White Horse — Chris Stapleton",
"Yohendrick Pinango": "Papaoutai (Afro Soul) — mikeeysmind",
"Anthony Santander": "Me Gusta (En Vivo) — Porfi Baloa",
"Charles McAdoo": "Yay Area — E-40",
"Jake Bloss": "Shower — Becky G",
"Max Scherzer": "Big Ego's — Dr. Dre, Hittman",
"Joe Mantiply": "Deliverance — Bubba Sparxxx",
"Andrés Giménez": "BOMBÓN — Daddy Yankee, El Alfa, Lil Jon",
"Bowden Francis": "Universal Sound — Tyler Childers",
"Addison Barger": "B.Y.O.B. — System Of A Down",
"Lenyn Sosa": "Yeshua — Holy Drill",
"Chase Lee": "The Lord Almighty Reigns (Psalm 93) — Sovereign Grace Music",
"Brendon Little": "Beggin' — Måneskin",
"Brandon Valenzuela": "Medley Cumbias Norteñas — Carín León",
"Lazaro Estrada": "Silencio Remix — Velito el Bufón",
"Cody Ponce": "La Grange — ZZ Top",
"Mason Fluharty": "Riot — Three Days Grace",
"Louie Varland": "Animal I Have Become — Three Days Grace",
"Yimi García": "Ven Espíritu Santo — Barak",
"Willie MacIver": "Dangerous World — Mustard, Travis Scott, YG",
"Justin Dean": "Life We Live (feat. Namond Lumpkin & Edgar Fletcher) — Project Pat · Namond Lumpkin · Edgar Fletcher",
"Matt Shaw": "LIFT MY HANDS — Forrest Frank",
"Cade Horton": "White Iverson — Post Malone",
"Moisés Ballesteros": "4K — El Alfa, Darell, Noriel",
"Edward Cabrera": "Tengo Mas — El Philippe",
"Ben Brown": "Starlight — Jon Pardi",
"Justin Steele": "God's Gonna Cut You Down — Johnny Cash",
"Jordan Wicks": "Wolves Cry — Bryan Martin",
"Porter Hodge": "Above The Clouds — Gang Starr · Inspectah Deck",
"Ethan Roberts": "Shine (feat. Marcus Stroman) — mike. · Marcus Stroman",
"Hoby Milner": "Barbie Girl — Aqua",
"Luke Little": "umean — Gunna",
"Hunter Harvey": "Real American — Rick Derringer",
"Drew Pomeranz": "Marianela (Que Pasa) — HUGEL",
"Daniel Palencia": "Gasolina — Daddy Yankee",
"Trent Thornton": "Lunatic Fringe — Red Rider",
"Jameson Taillon": "When the Levee Breaks — Led Zeppelin",
"Tyler Ferguson": "Heavy Eyes — Zach Bryan",
"Shelby Miller": "Just Like Johnny — Redferrin",
"Edwin Arroyo": "JOVEN LEYENDA — Myke Towers",
"Matt McLain": "Plug Walk — Rich The Kid",
"Dane Myers": "Still Tippin' — Mike Jones",
"Graham Ashcraft": "Hillbilly Deluxe — Brooks & Dunn, HARDY",
"Rhett Lowder": "OPPOSITE — Don Toliver",
"Chase Burns": "ONE CALL — Rich Amiri",
"Sal Stewart": "CAFé CON RON — Bad Bunny",
"TJ Friedl": "Would? — Alice In Chains",
"Connor Phillips": "Voices (Randy Orton) — Rev Theory",
"Brandon Williamson": "Are You Gonna Be My Girl — Jet",
"Blake Dunn": "The Stroke — Billy Squier",
"Chase Petty": "The Box — Roddy Ricch",
"Tony Santillan": "WWE: Hands Of Fate (Oba Femi) — def rebel",
"Zach Maxwell": "Man in the Box — Alice In Chains",
"Garrett Stubbs": "Golden Boy — Nadav Guedj",
"Matt Reynolds": "Big Lie — Post Malone",
"Justin Foscue": "Waves — Kanye West",
"Joey Estes": "I'm So Oakland — The Mekanix",
"Brian Serven": "God's Country — Blake Shelton",
"Blake Walston": "Ice Ice Baby — Vanilla Ice",
"Alec Gamboa": "My Town — Montgomery Gentry",
"Rece Hinds": "Love — Keyshia Cole",
"Tommy White": "Desperado — Rihanna",
"A.J. Puk": "Intro — Meek Mill",
"Adrian Del Castillo": "CORAÇAO - 20th Anniversary Mix — Jerry Ropero · HUGEL · Mijangos · Jesús Fernández",
"Andrew Saalfrank": "Bigger Than Me — Big Sean · The Flint Chozen Choir · Starrah",
"Brandyn Garcia": "Rump Shaker — Wreckx-N-Effect",
"Corbin Burnes": "Friends In Low Places — The Sounds Of Garth Brooks",
"Drey Jameson": "Dreams and Nightmares — Meek Mill",
"Jonathan Loáisiga": "Welcome To The Jungle — Guns N' Roses",
"Jordan Lawlar": "No Flex Just Faith — DIAMOND DISTRICT MUSIC",
"Jose Fernandez": "Chapa Pla Pla — Omega · Alofoke Music · B One El Productor De Oro",
"Juan Morillo": "Pa' Que Retozen — Tego Calderón",
"Justin Martinez": "Fireman — Lil Wayne",
"Kohl Drake": "The Chain - 2004 Remaster — Fleetwood Mac",
"Lourdes Gurriel Jr.": "Fácil - Prod. by Dj Honda x Roberto Ferrante — Bebeshito · Dj Honda · Roberto Ferrante",
"LuJames Groover": "I'm so Groovy — Future",
"Max Kepler": "Doin' Time — Sublime",
"Michael Soroka": "Interstate Love Song - 2019 Remaster — Stone Temple Pilots",
"Philip Abner": "Read Me My Rights — Brantley Gilbert",
"Ryan Waldschmidt": "The Way I Are — Timbaland · Keri Hilson · D.O.E.",
"Ryne Nelson": "Vampire - Feat. Whiteboy John — Tribal Seeds",
"Tommy Troy": "ORCHESTRATË — Yeat",
"Tyler Locklear": "Sour Patch Kids — Bryce Vine",
"Brent Rooker": "Hotel California - 2013 Remaster — Eagles",
"Darell Hernaiz": "VOY A LLeVARTE PA PR — Bad Bunny",
"Denzel Clarke": "Get It On The Floor — DMX · Swizz Beatz",
"Gunnar Hoglund": "Juke Box Hero — Foreigner",
"Justin Sterner": "Gasoline — Audioslave",
"Luis Morales": "Bendecido — Dale Pututi · Randy Malcom",
"Luis Severino": "Hermoso Momento - Remix — Farruko · Kairo Worship",
"Nick Kurtz": "Do I Wanna Know? — Arctic Monkeys",
"Zack Gelof": "Doin' Time — Sublime",
"Blaze Alexander": "STARGAZING — Travis Scott",
"Cade Povich": "Wonderwall — Oasis",
"Cameron Foster": "Evenflow — Pearl Jam",
"Chris Bassitt": "Growin' Up and Gettin' Old — Luke Combs",
"Christian Encarnacion-Strand": "White Horse — Chris Stapleton",
"Codi Heuer": "Wherever I May Roam — Metallica",
"Colton Cowser": "Work — Gang Starr",
"Félix Bautista": "Saxofones Mágicos — Los Avila",
"Heston Kjerstad": "Save a Horse (Ride a Cowboy) — Big & Rich",
"Jordan Westburg": "Like a Stone — Audioslave",
"Keegan Akin": "Animals — Nickelback",
"Reed Trimble": "Arkansas — Chris Stapleton",
"Ryan Helsley": "Hells Bells — AC/DC",
"Ryan Mountcastle": "Dear Maria, Count Me In — All Time Low",
"Trey Gibson": "Stranglehold — Ted Nugent",
"Yaramil Hiraldo": "Vivir Mi Vida — Marc Anthony",
"Yosver Zulueta": "Nada Me Afecta — El Kamel · El Dany MG",
"Zach Eflin": "Heartache Tonight - 2013 Remaster — Eagles",
"Brayan Bello": "La Fama 21 — Don Miguelo · Lapiz Conciente",
"Brett Harris": "Psalms 139 — Caleb Gordon",
"Eduardo Rivera": "JOVEN LEYENDA — Myke Towers",
"Erik Miller": "A Milli - Album Version (Edited) — Lil Wayne",
"Garrett Crochet": "Rooster (2022 Remaster) — Alice In Chains",
"Isiah KinerFalefa": "What Did I Miss? — Drake",
"Jahmai Jones": "Hi Roller — Lil Uzi Vert",
"Jake Bennett": "Tulsa Time — Don Williams",
"Johan Oviedo": "Amazing — Kanye West · Jeezy",
"Jovani Moran": "JOVEN LEYENDA — Myke Towers",
"Kristian Campbell": "Thuggish Ruggish Bone — Bone Thugs-N-Harmony",
"Kutter Crawford": "Cut It (feat. Young Dolph) — O.T. Genasis · Young Dolph",
"Mickey Gasper": "What's My Name - Album Version (Edited) — DMX",
"Nate Eaton": "Blue World — Mac Miller",
"Nick Sogard": "It Feels So Good — Sonique",
"Patrick Sandoval": "What's the Use? — Mac Miller",
"Ranger Suárez": "Mr. Rager — Kid Cudi",
"Roman Anthony": "The Spins — Mac Miller · Empire Of The Sun",
"Romy Gonzalez": "Sundream — RÜFÜS DU SOL",
"Seth Martinez": "Gotta Have It — JAY-Z · Kanye West",
"Tanner Houck": "Programs — Mac Miller",
"Trevor Story": "Programs — Mac Miller",
"Triston Casas": "prada dem (feat. Offset) — Gunna · Offset",
"Tsung-Che Cheng": "Fast Car — Luke Combs",
"Willson Contreras": "SONRÍELE — Daddy Yankee",
"Zack Kelly": "DEVIL — Shinedown",
"Braxton Garrett": "Pork And Beans — Weezer",
"Clay Holmes": "White Horse — Chris Stapleton",
"Ryan Zeferjahn": "Welcome to the Show — Cody Johnson"
},
"history": {
"Brent Rooker": [
{
"t": "Hotel California - 2013 Remaster",
"a": "Eagles",
"d": "6/23/2025"
},
{
"t": "Edge of Seventeen",
"a": "Stevie Nicks",
"d": "4/10/2024"
}
],
"Darell Hernaiz": [
{
"t": "VOY A LLeVARTE PA PR",
"a": "Bad Bunny",
"d": "3/8/2026"
},
{
"t": "Broke Boys",
"a": "Drake · 21 Savage",
"d": "8/17/2025"
},
{
"t": "De Museo",
"a": "Bad Bunny",
"d": "4/10/2024"
}
],
"Luis Severino": [
{
"t": "Hermoso Momento - Remix",
"a": "Farruko · Kairo Worship",
"d": "10/13/2025"
},
{
"t": "Altar",
"a": "Hulvey · Forrest Frank",
"d": "4/24/2024"
}
],
"Nick Kurtz": [
{
"t": "Do I Wanna Know?",
"a": "Arctic Monkeys",
"d": "4/4/2026"
},
{
"t": "WHISKEY WHISKEY (feat. Morgan Wallen)",
"a": "Moneybagg Yo · Morgan Wallen",
"d": "8/15/2025"
},
{
"t": "GOOD TIME",
"a": "Niko Moon",
"d": "5/28/2025"
}
],
"Zack Gelof": [
{
"t": "Doin' Time",
"a": "Sublime",
"d": "5/1/2026"
},
{
"t": "не расслабляйся",
"a": "Skryptonite",
"d": "8/20/2025"
},
{
"t": "Toosie Slide",
"a": "Drake",
"d": "6/21/2024"
}
],
"Joey Wentz": [
{
"t": "Be (Intro)",
"a": "Common",
"d": "10/29/2025"
},
{
"t": "Team",
"a": "Lorde",
"d": "6/20/2024"
}
],
"Corbin Carroll": [
{
"t": "E85",
"a": "Don Toliver",
"d": "7/21/2026"
},
{
"t": "National Treasures",
"a": "Drake",
"d": "7/8/2026"
},
{
"t": "waves - Tame Impala Remix",
"a": "Miguel · Tame Impala",
"d": "4/7/2026"
}
],
"Eduardo Rodriguez": [
{
"t": "Jamaican (Bam Bam)",
"a": "HUGEL · SOLTO (FR)",
"d": "4/22/2026"
},
{
"t": "Juana Polinaria / Como loco-funche",
"a": "Tambor Urbano",
"d": "3/12/2026"
},
{
"t": "capaz (merengueton)",
"a": "Alleh · Yorghaki",
"d": "4/28/2025"
}
],
"Gabriel Moreno": [
{
"t": "Taboo",
"a": "Don Omar",
"d": "5/1/2026"
},
{
"t": "Amado Mio",
"a": "Jose \"Papo\" Rivera",
"d": "5/1/2026"
},
{
"t": "NERVIOS DE ACERO (Bandido)",
"a": "Farruko · Louis BPM · Fronti",
"d": "10/6/2025"
}
],
"Geraldo Perdomo": [
{
"t": "El Mejor - Remix",
"a": "Yeison Jimenez · Chayín Rubio",
"d": "8/7/2026"
},
{
"t": "Bendecido",
"a": "Bryant Myers",
"d": "8/4/2026"
},
{
"t": "Cancion del Mariachi (Desperado) [Antonio Banderas guitar]",
"a": "LucasGitanoFamily",
"d": "8/4/2026"
},
{
"t": "Sauce Boy Freestyle 4",
"a": "Eladio Carrion",
"d": "7/19/2026"
},
{
"t": "American Nights",
"a": "Zach Bryan",
"d": "7/5/2026"
},
{
"t": "Sonríele",
"a": "Daddy Yankee",
"d": "6/3/2026"
},
{
"t": "agarrao de DIOS",
"a": "Madiel Lara",
"d": "5/19/2026"
},
{
"t": "¿Quién Podrá? - Live",
"a": "Averly Morillo",
"d": "4/22/2026"
},
{
"t": "LEÓN (LION)",
"a": "Elevation Worship · Elevation Español",
"d": "4/18/2026"
},
{
"t": "Ella Me Vivia",
"a": "El Prodigio",
"d": "3/15/2026"
},
{
"t": "Mesias - Live",
"a": "Averly Morillo",
"d": "10/6/2025"
}
],
"Ildemaro Vargas": [
{
"t": "Oh Yeah",
"a": "Yello",
"d": "7/5/2026"
},
{
"t": "ACHO PR",
"a": "Bad Bunny · Arcángel · De La Ghetto · Ñengo Flow",
"d": "4/18/2026"
},
{
"t": "Sufriendo",
"a": "MYLØ · Zafra Negra",
"d": "6/13/2024"
}
],
"James McCann": [
{
"t": "El Campeón",
"a": "El Kimiko y Yordy · Michel Boutic · EL YORDY DK",
"d": "4/22/2026"
},
{
"t": "Hard Fought Hallelujah",
"a": "Brandon Lake",
"d": "10/6/2025"
}
],
"Jorge Barrosa": [
{
"t": "I Adore You (feat. Daecolm)",
"a": "HUGEL · Topic · Arash · Daecolm",
"d": "8/7/2026"
},
{
"t": "MOOD BRAZIL",
"a": "Lil Naay",
"d": "7/21/2026"
},
{
"t": "Hermoso Momento - Radio Edit",
"a": "Kairo Worship",
"d": "7/20/2026"
},
{
"t": "Si Dios Me Hubiera Dicho",
"a": "Juan Vegas",
"d": "4/18/2026"
},
{
"t": "It Feels So Good",
"a": "Matt Sassari · HUGEL · Sonique",
"d": "10/6/2025"
},
{
"t": "Suelto",
"a": "Sarai Rivera",
"d": "10/6/2025"
}
],
"Juan Morillo": [
{
"t": "Pa' Que Retozen",
"a": "Tego Calderón",
"d": "4/23/2026"
},
{
"t": "HORA CERO",
"a": "Myke Towers",
"d": "10/6/2025"
}
],
"Ketel Marte": [
{
"t": "PANTI Y COLALE 2.0",
"a": "El Alfa · De La Ghetto · Zion · DJ Chulo NYC · El Cherry Scom · La Greña · Ronny GTA · Ezzy R",
"d": "8/7/2026"
},
{
"t": "Ta Celoso",
"a": "Ezzy R · Megadivo Produce",
"d": "7/19/2026"
},
{
"t": "Shorty - Remix",
"a": "Yailin la Mas Viral · Ezzy R",
"d": "7/5/2026"
},
{
"t": "Nadie Me Miente",
"a": "Papera · Karola · El Baby R",
"d": "6/25/2026"
},
{
"t": "Replica (feat. El Alfa)",
"a": "CJ · El Alfa",
"d": "5/19/2026"
},
{
"t": "Hagan De To Meno Daño",
"a": "Ezzy R · KiK1 STW · Ronny GTA",
"d": "4/24/2026"
},
{
"t": "Pose",
"a": "Daddy Yankee",
"d": "4/22/2026"
},
{
"t": "Aro Aro Baby",
"a": "Dj Scuff",
"d": "4/18/2026"
},
{
"t": "El Sobaito",
"a": "Geovanny Polanco",
"d": "3/12/2026"
},
{
"t": "3 Leches",
"a": "El Alfa",
"d": "10/6/2025"
}
],
"Lars Nootbaar": [
{
"t": "Brighter",
"a": "RÜFÜS DU SOL",
"d": "6/18/2026"
},
{
"t": "Oh Boy",
"a": "Cam'ron · Juelz Santana",
"d": "9/3/2025"
}
],
"Max Kepler": [
{
"t": "Doin' Time",
"a": "Sublime",
"d": "6/30/2026"
},
{
"t": "Diablo",
"a": "Mac Miller",
"d": "9/10/2025"
},
{
"t": "IM GLASHAUS MIT SCHEINEN WERFEN",
"a": "makko · lucidbeatz",
"d": "9/8/2025"
},
{
"t": "How Soon Is Now?",
"a": "The Smiths",
"d": "8/5/2025"
},
{
"t": "Day 'N' Nite (nightmare)",
"a": "Kid Cudi",
"d": "5/14/2025"
},
{
"t": "White Bronco",
"a": "Action Bronson",
"d": "4/7/2025"
}
],
"Merrill Kelly": [
{
"t": "Under Ground Kings",
"a": "Drake",
"d": "6/5/2026"
},
{
"t": "Ante Up (Robbin Hoodz Theory) - Radio Version",
"a": "M.O.P.",
"d": "5/19/2022"
}
],
"Nolan Arenado": [
{
"t": "TOO COOL TO BE CARELESS",
"a": "PAWSA",
"d": "4/18/2026"
},
{
"t": "OE OE",
"a": "Farruko · Louis BPM",
"d": "3/15/2026"
},
{
"t": "Brujeria",
"a": "El Gran Combo De Puerto Rico",
"d": "3/7/2026"
},
{
"t": "If You Know You Know",
"a": "Pusha T",
"d": "12/22/2025"
}
],
"Tim Tawa": [
{
"t": "Remember the Name (feat. Styles of Beyond)",
"a": "Fort Minor · Styles Of Beyond",
"d": "4/18/2026"
},
{
"t": "What's Luv? (feat. Ashanti)",
"a": "Fat Joe · Ashanti",
"d": "10/6/2025"
},
{
"t": "By Your Side",
"a": "Rod Wave",
"d": "5/11/2025"
}
],
"Tyler Locklear": [
{
"t": "Sour Patch Kids",
"a": "Bryce Vine",
"d": "7/19/2026"
},
{
"t": "Marley Vibez (feat. Money Man)",
"a": "TEC · Money Man",
"d": "9/18/2025"
}
],
"Adrian Del Castillo": [
{
"t": "CORAÇAO - 20th Anniversary Mix",
"a": "Jerry Ropero · HUGEL · Mijangos · Jesús Fernández",
"d": "7/20/2026"
},
{
"t": "GLORIA A ÉL",
"a": "Daddy Yankee",
"d": "4/22/2026"
}
],
"Jose Fernandez": [
{
"t": "Chapa Pla Pla",
"a": "Omega · Alofoke Music · B One El Productor De Oro",
"d": "4/24/2026"
},
{
"t": "Chapa Pla Pla - Prod. by B One El Productor De Oro",
"a": "Omega · Alofoke Music · B One El Productor De Oro",
"d": "4/24/2026"
},
{
"t": "El Campeón",
"a": "El Kimiko y Yordy · Michel Boutic · EL YORDY DK",
"d": "4/18/2026"
}
],
"Justin Martinez": [
{
"t": "Fireman",
"a": "Lil Wayne",
"d": "11/6/2025"
},
{
"t": "Catalina Toma Mas Guaracha",
"a": "JMRodriguez",
"d": "6/17/2025"
},
{
"t": "Baila Conmigo (feat. Kelly Ruiz)",
"a": "Dayvi · Victor Cardenas · Kelly Ruíz",
"d": "4/30/2024"
}
],
"Lourdes Gurriel Jr.": [
{
"t": "Fácil - Prod. by Dj Honda x Roberto Ferrante",
"a": "Bebeshito · Dj Honda · Roberto Ferrante",
"d": "7/5/2026"
},
{
"t": "El Mechón",
"a": "Banda MS de Sergio Lizárraga",
"d": "5/5/2026"
},
{
"t": "Vidrado Em Você",
"a": "Dj Guuga · Mc Livinho",
"d": "4/21/2026"
},
{
"t": "Thick Of It (feat. Trippie Redd)",
"a": "KSI · Trippie Redd",
"d": "10/31/2025"
},
{
"t": "Goza Pelota",
"a": "El Taiger · Adonis MC",
"d": "9/4/2025"
},
{
"t": "Yo Lo Se",
"a": "Yomil y El Dany",
"d": "4/5/2024"
}
],
"Brandon Young": [
{
"t": "Cold",
"a": "Crossfade",
"d": "5/8/2026"
},
{
"t": "Power of Soul",
"a": "Jimi Hendrix",
"d": "8/27/2025"
}
],
"Cade Povich": [
{
"t": "Wonderwall",
"a": "Oasis",
"d": "8/5/2026"
},
{
"t": "Everything I Love",
"a": "Morgan Wallen",
"d": "5/8/2026"
}
],
"Carlos Narváez": [
{
"t": "Heartless",
"a": "Kanye West",
"d": "6/16/2026"
},
{
"t": "Somos de Calle",
"a": "Daddy Yankee",
"d": "6/30/2025"
}
],
"Christian Encarnacion-Strand": [
{
"t": "White Horse",
"a": "Chris Stapleton",
"d": "6/18/2026"
},
{
"t": "I Need A Ghost",
"a": "Brandon Lake",
"d": "4/14/2025"
}
],
"Coby Mayo": [
{
"t": "AT THE PARTY (feat. Pharrell Williams, Travis Scott)",
"a": "Kid Cudi · Pharrell Williams · Travis Scott",
"d": "4/27/2026"
},
{
"t": "Man Made A Bar",
"a": "Morgan Wallen · Eric Church",
"d": "8/18/2025"
}
],
"Pete Alonso": [
{
"t": "Money for Nothing",
"a": "Dire Straits",
"d": "6/16/2026"
},
{
"t": "Money For Nothing",
"a": "Dire Straits",
"d": "6/13/2026"
},
{
"t": "Make It Rain",
"a": "Fat Joe · Lil Wayne",
"d": "3/23/2026"
},
{
"t": "Layla",
"a": "Derek & The Dominos",
"d": "4/5/2025"
}
],
"Shane Baz": [
{
"t": "Rooster (2022 Remaster)",
"a": "Alice In Chains",
"d": "7/8/2026"
},
{
"t": "Rooster",
"a": "Alice In Chains",
"d": "2/26/2026"
}
],
"Tyler O'Neill": [
{
"t": "The Motto",
"a": "Drake · Lil Wayne",
"d": "5/11/2026"
},
{
"t": "FE!N (feat. Playboi Carti)",
"a": "Travis Scott · Playboi Carti",
"d": "7/28/2025"
}
],
"Yohel Pozo": [
{
"t": "capaz (merengueton)",
"a": "Alleh · Yorghaki",
"d": "8/5/2026"
},
{
"t": "Astronaut In The Ocean",
"a": "Masked Wolf",
"d": "8/17/2025"
}
],
"Chris Bassitt": [
{
"t": "Growin' Up and Gettin' Old",
"a": "Luke Combs",
"d": "9/18/2024"
},
{
"t": "God's Country",
"a": "Blake Shelton",
"d": "4/12/2024"
}
]
}
};
